### ISSUE TITLE
Aliucord's TapTap by Vendicated and Diamond 

### ISSUE THREAD

**Issue by synapsister** [vendetta-mod/ideas#100]
### Discord username

@synapsissy

### Plugin description

it's allows you to double tap someone else's message to quickly reply and double tap on your own messages to quickly edit them.

### Elaborate

The original plugin also comes with 4 settings
• the ability to adjust the adjust the double tap window in ms (200 by default)
• hiding the reply/edit buttons from the message interaction interface 
• automatically opening the keyboard when replying to a message
• making it so that double tapping your own messages makes you reply to them, not edit

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
[already exists](https://vd-plugins.github.io/proxy/github.com/acquitelol/better-chat-gestures/releases/latest/download/), if you want to suggest something do so in the plugin author's repo/plugin channel

**Comment by Darksound9** [comment]
@Gabe616 That link returns a 404. Assuming that is BetterChatGestures, links to that plugin in the discord server also return 404.

**Comment by Cynosphere** [comment]
Copy it, go into Plugins, click add, paste.

**Comment by Darksound9** [comment]
Thanks! That worked. Not sure why I'm downvoted as I'm sure many new users will also not know that.

**Comment by Cynosphere** [comment]
The client should tell you "This link is a Plugin, would you like to install it?" when you click on it in the app though

**Comment by Darksound9** [comment]
It's not showing in the plugin channel. When I search for (and then click) a link for it in #playground, Vendetta doesn't prompt me--opens in browser which renders the 404.

Running Xiaomi Poco F3 / MIUI 14.

I digress--won't blow up this thread further. Hope this helps!
