### ISSUE TITLE
Account switcher from aliucord

### ISSUE THREAD

**Issue by Abinash-G** [vendetta-mod/ideas#102]
### Discord username

abimadhu

### Plugin description

**This account switcher have local token saving feature in xml file**
- we can save more than 5 accounts without limits
- easily backup account tokens in internal storage and cloud sync
- account can be easily recovered if password forgotten

### ​

- [X] I have verified that this request is indeed original

**Comment by mollyvita** [comment]
>save without limits

same as #34

**Comment by Abinash-G** [comment]
Ohh,yes but this one is better than default one tho!!!
Pls make one plugin

**Comment by mollyvita** [comment]
> Ohh,yes but this one is better than default one tho!!! Pls make one plugin

your issue is duplicate, dude

**Comment by karasi-online** [comment]
HI FISH
