### ISSUE TITLE
LocalPin

### ISSUE THREAD

**Issue by AGuyNamedRakkun** [vendetta-mod/ideas#103]
### Discord username

@ifuckedyourmomlastnight

### Plugin description

Same as the enmity's LocalPin addon. Here is their description: 

> Long press on message and select "pin message locally". And now you can see those messages in same way as you see normal pinned messages

Would be cool to have an option to see them all together like Aliucord's Local Pin plugin along with that. 

### Elaborate

Like I said above it would be great if this plugin enables us to pin messages on client side (locally) so that we could see them on the pinned messages, along with another option where we could have a tab to see all of them together too. Having both of these options would be cool but I know it would take lots of time to develop too.

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
grabbing this

**Comment by AGuyNamedRakkun** [comment]
Hey @Gabe616, thanks for deciding to work on this. Hit me up if you need someone to test.

**Comment by nexpid** [comment]
almost done with this 

https://github.com/vendetta-mod/ideas/assets/60316309/0908e87b-6146-49b1-b808-8794d0340722

**Comment by nexpid** [comment]
plugin is mostly done, you can add it here: `https://vendetta.nexpid.xyz/local-pins`
lmk if you find something that needs fixing

**Comment by han-anag** [comment]
> plugin is mostly done, you can add it here: `https://vendetta.nexpid.xyz/local-pins`
> lmk if you find something that needs fixing

Installed it just now, doesn't work unfortunately. It won't even let me turn it on.
![Screenshot_20230817-195836.jpg](https://github.com/vendetta-mod/ideas/assets/114708039/2ea0feb0-b818-4360-9d43-0269baabd0cf)

**Comment by nexpid** [comment]
in that case checks debug logs, thank

**Comment by AGuyNamedRakkun** [comment]
Hey @Gabe616, here is the debug log.

![1000003233.jpg](https://github.com/vendetta-mod/ideas/assets/130555117/8bd79485-6002-477e-aaa5-d9ef0c6dc731)

**Comment by nexpid** [comment]
the error you provided doesn't seem to happen to me (and doesn't even make sense), try refetching the plugin

**Comment by AGuyNamedRakkun** [comment]
It works now after re fetching. Let me know if I should close this issue after plugin gets proxied.

**Comment by han-anag** [comment]
Can confirm it works for me now after refetching

**Comment by nexpid** [comment]
@Cynosphere also finished, https://vd-plugins.github.io/proxy/vendetta.nexpid.xyz/local-pins/
