### ISSUE TITLE
Hide servers

### ISSUE THREAD

**Issue by Fairyyfeelings** [vendetta-mod/ideas#107]
### Plugin description

A remake of Betterdiscord's HideServer plugin. Allows you to hide certain servers. 

### Elaborate

Has an option for server visibility upon long pressing. 

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
grabbing this

**Comment by nexpid** [comment]
wip https://github.com/vendetta-mod/ideas/assets/60316309/68a44dd9-f07e-4777-98fc-216ddab98694

**Comment by nexpid** [comment]
plugin done!! you can test it here: `https://vendetta.nexpid.xyz/hide-servers`
lmk if you find any bugs

**Comment by nexpid** [comment]
https://vd-plugins.github.io/proxy/vendetta.nexpid.xyz/hide-servers
(forgot to send the link)
