### ISSUE TITLE
Vendetta OLED

### ISSUE THREAD

**Issue by Call-Me-Doc** [vendetta-mod/ideas#11]
### Discord username

@callmedoc_

### Theme description

a theme based on the vendetta logo, using the teal blue as it's primary color, and then OLED black bc I like my blacks being actually black.

### More details

the theme should have vendetta's blue as it's primary color, for things that would usually be burple, and work off of the experimental OLED.

### ​

- [X] I have verified that this request is indeed original

**Comment by TakiShiwa** [comment]
I'll work on it from 2nd of July.
If you want to talk about anything my discord username is @taki_shiwa

**Comment by TakiShiwa** [comment]
You can mark it work on progress

**Comment by TakiShiwa** [comment]
Finally completed the theme you can go & check it out here
https://discord.com/channels/1015931589865246730/1125716762097373234/1125716762097373234
