### ISSUE TITLE
Spotify Listen Along feature

### ISSUE THREAD

**Issue by Rairof** [vendetta-mod/ideas#113]
### Discord username

Rairof

### Plugin description

Simply Spotify listen along feature port from PC would be nice.

### Elaborate

Would be better if we can send listen along invited in a similar way like we do in desktop discord 'through the + icon) I see the invite being expired on Mobile discord when changing songs but it being updated to current playing song in PC, it would be nice that it would not expire and auto update to current song playing in Spotify like on PC in mobile.

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
already exists in my [NexxUtils](https://vendetta.nexpid.xyz/nexxutils) plugin (unproxied and wip)

**Comment by Rairof** [comment]
> already exists in my [NexxUtils](https://vendetta.nexpid.xyz/nexxutils) plugin (unproxied and wip)

I mean, does it fixes the issues I stated on Elaborate catagory?

**Comment by nexpid** [comment]
> > already exists in my [NexxUtils](https://vendetta.nexpid.xyz/nexxutils) plugin (unproxied and wip)
> 
> I mean, does it fixes the issues I stated on Elaborate catagory?

https://tryitands.ee

**Comment by Rairof** [comment]
> > > already exists in my [NexxUtils](https://vendetta.nexpid.xyz/nexxutils) plugin (unproxied and wip)
> > 
> > 
> > I mean, does it fixes the issues I stated on Elaborate catagory?
> 
> https://tryitands.ee

Can't, try and see if I can't send invites...

**Comment by nexpid** [comment]
> > > > already exists in my [NexxUtils](https://vendetta.nexpid.xyz/nexxutils) plugin (unproxied and wip)
> > > 
> > > 
> > > I mean, does it fixes the issues I stated on Elaborate catagory?
> > 
> > 
> > [tryitands.ee](https://tryitands.ee)
> 
> Can't, try and see if I can't send invites...

it works the exact same way as it does on PC, you press on the listen along button and you're synced with the user until you switch songs

**Comment by Rairof** [comment]
> > > > > already exists in my [NexxUtils](https://vendetta.nexpid.xyz/nexxutils) plugin (unproxied and wip)
> > > > 
> > > > 
> > > > I mean, does it fixes the issues I stated on Elaborate catagory?
> > > 
> > > 
> > > [tryitands.ee](https://tryitands.ee)
> > 
> > 
> > Can't, try and see if I can't send invites...
> 
> it works the exact same way as it does on PC, you press on the listen along button and you're synced with the user until you switch songs

The issue is not with listen along button, it's with the listen along invites in mobile, would be nice if we could send invites and it behaves similar to PC (sync with current songs instead of expire when changing songs) ones still it gives the option to listen along so I'll close this post as not complete

**Comment by nexpid** [comment]
> > > > > > already exists in my [NexxUtils](https://vendetta.nexpid.xyz/nexxutils) plugin (unproxied and wip)
> > > > > 
> > > > > 
> > > > > I mean, does it fixes the issues I stated on Elaborate catagory?
> > > > 
> > > > 
> > > > [tryitands.ee](https://tryitands.ee)
> > > 
> > > 
> > > Can't, try and see if I can't send invites...
> > 
> > 
> > it works the exact same way as it does on PC, you press on the listen along button and you're synced with the user until you switch songs
> 
> The issue is not with listen along button, it's with the listen along invites in mobile, would be nice if we could send invites and it behaves similar to PC (sync with current songs instead of expire when changing songs) ones still it gives the option to listen along so I'll close this post as not complete

???? there are no invites on desktop??

**Comment by Rairof** [comment]
Let me record the issue and show in discord instead

**Comment by nexpid** [comment]
k

**Comment by Rairof** [comment]
Yeah, it's a issue I think I got cause of the invite expiring few mins after I sent I think
