### ISSUE TITLE
Text box avatar

### ISSUE THREAD

**Issue by ahar2611** [vendetta-mod/ideas#114]
### Discord username

Lanneysempai

### Plugin description

Aliucord had a plugin that added your own avatar to the left side of the text bar. It was really good for changing status quickly (tap and hold) and viewing your own profile without sending a message (tap). Port that plugin pls.

![SPOILER_Screenshot_20211128-120313](https://github.com/vendetta-mod/ideas/assets/82914887/83b18554-b7db-45b1-ab6a-47702e7bbce9)

### ​

- [x] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Claiming

**Comment by Cynosphere** [comment]
Done, awaiting proxy before closing.

**Comment by Cynosphere** [comment]
https://vd-plugins.github.io/proxy/cynosphere.github.io/VendettaPlugins/ChatboxAvatar/
