### ISSUE TITLE
USRPFP/external custom avatars

### ISSUE THREAD

**Issue by Nonstopgaming75** [vendetta-mod/ideas#115]
### Plugin description

i recently saw that some guys made a fully working css theme that shows animated pfps, although this is for css only so it can't be used on vendetta.
Is there someone who's able to convert the theme or make a plugin based on what this guys already done.

linking the discord server the repo and github raws:
https://discord.gg/3n9CEkMGKz
https://raw.githubusercontent.com/Yeetov/USRPFP-Reborn/main/src/dist/source.css
https://github.com/Yeetov/USRPFP-Reborn

### Elaborate

This plugin/theme should be supported by a server just like usrbg where people can upload their gif and this will be moderated to check if it's acceptable or not, then the bot will modify the database adding a line for the user id and animated pfp.
the theme/plugin will then substitute the avatar url with the url of the gif making it possible for other users that has the same plugin/theme to see it.

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Title is misleading, should be "external custom avatars", "USRPFP", or something of the sort

**Comment by Nonstopgaming75** [comment]
oh sorry, i just edited the title, do u think this could be made tho?

**Comment by nexpid** [comment]
> oh sorry, i just edited the title, do u think this could be made tho?

most likely yes

**Comment by Nonstopgaming75** [comment]
> > oh sorry, i just edited the title, do u think this could be made tho?
> 
> most likely yes

hope someone will claim it

**Comment by nexpid** [comment]
claiming lol

**Comment by Nonstopgaming75** [comment]
> claiming lol

fr, thk u so much!

**Comment by nexpid** [comment]
i've decided i don't want to claim this idea anymore after looking more into USRPFP reborn

**Comment by Nonstopgaming75** [comment]
> i've decided i don't want to claim this idea anymore after looking more into USRPFP reborn

why tho? is there something particular that made u change ur mind?

**Comment by Vendicated** [comment]
USRPFP has several flaws

They for some reason use repl over hosting it on github and seem to be allowing arbitrary image hosts, such as the following (all taken from their current stylesheet):
- https://emoji.discadia.com/emojis/88387ea8-43b1-47fa-999c-5c57a61a6661.GIF
- https://html-usrpfp.fatalfang.repl.co/ScamBan.png
- https://cdn.dribbble.com/users/345826/screenshots/1820014/big-hero-6.gif
- https://cdn-old.brawlify.com/brawler-bs/Surge.png

This is very bad because it allows owners of any of these sites to track you, your ip (thus location), your habits

one of the stylesheets they load, found at <https://html-usrpfp.adiprakash53071.repl.co/avatars.css?_=1>, isn't even valid css.
![image](https://github.com/vendetta-mod/ideas/assets/45497981/493f068b-71de-40de-93d7-ddca25b086ea)

**Comment by Cynosphere** [comment]
If someone still wants to do this on their own accord, go ahead, but this is just mismanaged and too much of a risk to be "endorsed" by having it proxied.

(If they fix everything brought to attention I will reopen)

**Comment by Yeetov** [comment]
I didn't really have any contact with the publisher, I created USRPFP Reborn for Vencord

Username: FoxStorm1 
![Screenshot_20230829-071732](https://github.com/vendetta-mod/ideas/assets/69159547/6c69fcbc-8c13-4f2e-bf75-33799af42457)
What steps could I do to make it not a privacy issue. I am hosting it on replit so it is easy to update. I don't mind hosting it on GitHub though

**Comment by Yeetov** [comment]
Now all the of the custom avatars are hosted on Imgur and Imgbb, database is hosted on GitHub
[https://raw.githubusercontent.com/Yeetov/USRPFP-Reborn/main/avatarsdatabase.css](https://raw.githubusercontent.com/Yeetov/USRPFP-Reborn/main/avatarsdatabase.css)

**Comment by nexpid** [comment]
hi i reworked USRPFP reborn reopen the issue and assign me thanks

**Comment by nexpid** [comment]
plugin finished: https://vendetta.nexpid.xyz/usrpfp

**Comment by nexpid** [comment]
proxied https://vd-plugins.github.io/proxy/vendetta.nexpid.xyz/usrpfp/
