### ISSUE TITLE
Plain Folder Icon

### ISSUE THREAD

**Issue by MonkeyMechanic** [vendetta-mod/ideas#116]
### Discord username

TheyMonkeyMechanic

### Plugin description

This plugin hides the guild icons when grouped in a folder.

### Elaborate

This plugin would hide guild images in folder icons, showing only a colored folder. This plugin exists in Vencord as PlainFolderIcon by botato. This doesn't do much more than that.

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Duplicate of #66 and #93
