### ISSUE TITLE
Updated or Better implementation of HideBlockedMessages

### ISSUE THREAD

**Issue by bleelblep** [vendetta-mod/ideas#12]
### Plugin description

There is a plugin called HideBlockedMessages but it doesn't load constantly and sometimes needs a refresh / close and reopen for it to be activated.

I would like either an update or a new implementation of any HideBlockedMessages type plugin that works consistently and 100% of the time. 

### ​

- [X] I have verified that this request is indeed original

**Comment by wingio** [comment]
Request any features or fixes on the respective plugins repo
