### ISSUE TITLE
Better status a port from aliucord

### ISSUE THREAD

**Issue by Adara1120** [vendetta-mod/ideas#121]
### Discord username

adarabluelanterncorpsentity

### Plugin description

It would be cool if we could change the color of our status  like make the active color purple instead of green

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Already possible via Themes+ icon recoloring.

**Comment by Adara1120** [comment]
> Already possible via Themes+ icon recoloring.

Really? I'm sorry for not knowing forgive me of my ignorance please
