### ISSUE TITLE
Playable embeds

### ISSUE THREAD

**Issue by Adara1120** [vendetta-mod/ideas#124]
### Discord username

adarabluelanterncorpsentity

### Plugin description

Allows you to play a YouTube video or Spotify song in the embed

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Watching YouTube within Discord is already a stock feature
Spotify: https://vd-plugins.github.io/proxy/fres621.github.io/vendetta-plugins/SpotifyPreview/

**Having it actually play inline with chat is not possible due to chat being rendered natively.**

**Comment by Adara1120** [comment]
I'm sorry I've only ever used aliucord and wanted features from there on vendetta I like it more
