### ISSUE TITLE
AudioPlayer

### ISSUE THREAD

**Issue by MarselTheLynx** [vendetta-mod/ideas#125]
### Discord username

@midicat228

### Plugin description

A plugin that allows you to listen to audio files inside of Discord without downloading them, like on PC

### Elaborate

No

### ​

- [X] I have verified that this request is indeed original

**Comment by rickdtc** [comment]
https://github.com/vendetta-mod/ideas/assets/74096544/48a8a741-1e4a-4a9e-97c2-c1b573a406ec

I mean you could just use Custom Voice Messages plugin

**Comment by MarselTheLynx** [comment]
Based plugin
