### ISSUE TITLE
Bluecord warn

### ISSUE THREAD

**Issue by Not-Baguette** [vendetta-mod/ideas#127]
### Discord username

bagubaguu

### Plugin description

A new badge to warn people that is in Bluecord discord server in your chat. 

### Elaborate

An automatically updated SQL database of everyone in Bluecord's discord server, if they text in the current chat the plugin user in, it will show a "!" Badge beside it's name.

### ​

- [X] I have verified that this request is indeed original

**Comment by rickdtc** [comment]
Real
