### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by rodney528** [vendetta-mod/ideas#13]
### Discord username

@rodney528

### Plugin description

Set timestamps to people and make them with a command.

### ​

- [x] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
[Exists](https://gabe616.github.io/VendettaPlugins/better-timestamps) but not proxied yet.

**Comment by redstonekasi** [comment]
https://vd-plugins.github.io/proxy/gabe616.github.io/VendettaPlugins/better-timestamps/

**Comment by rodney528** [comment]
> [Exists](https://gabe616.github.io/VendettaPlugins/better-timestamps) but not proxied yet.

Ah thx
