### ISSUE TITLE
ClearURLs from Vencord to Vendetta

### ISSUE THREAD

**Issue by XAlboX** [vendetta-mod/ideas#133]
### Discord username

@alboook

### Plugin description

It will be more effective than TextReplace, we can keep that one for something else, just like Vencord does...

### Elaborate

It would be nice if the plugin could remove the tracking parameters from the urls of YT, Instagram etc.

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
grabbing

**Comment by Cynosphere** [comment]
Duplicate of #45
