### ISSUE TITLE
Free soundboard on phone

### ISSUE THREAD

**Issue by DARK-VIDER** [vendetta-mod/ideas#134]
### Discord username

_darkvider

### Plugin description

A plugin that allows the user to get discord soundboard on phone and use it for free

### ​

- [x] I have verified that this request is indeed original

**Comment by nexpid** [comment]
> > **Examples of impossible plugins**
> Free nitro - Everything except sending emotes and stickers

that includes soumrboard

**Comment by DARK-VIDER** [comment]
> > > **Examples of impossible plugins**
> > Free nitro - Everything except sending emotes and stickers
> 
> that includes soumrboard

Oh ok that makes sense
