### ISSUE TITLE
Freecon

### ISSUE THREAD

**Issue by Rairof** [vendetta-mod/ideas#136]
### Discord username

@rairof

### Plugin description

since freemoji exists, freemix plugin is not needed as remix can be enabled through experiments now, How about discord icons feature plugin unlocked for everyone without nitro (if possible ofcourse).
![image](https://github.com/vendetta-mod/ideas/assets/107706560/61b2bcab-60cf-4dbb-85c2-a31c79469718)
![image](https://github.com/vendetta-mod/ideas/assets/107706560/917106b4-377c-4903-b9b7-48f280b36733)

### Elaborate

enables app icon feature for everyone for free

### ​

- [X] I have verified that this request is indeed original

**Comment by Dziurwa14** [comment]
done
https://vd-plugins.github.io/proxy/dziurwa14.github.io/vendetta-plugins/Freecons/
