### ISSUE TITLE
Audio Player Embed

### ISSUE THREAD

**Issue by SixthByte** [vendetta-mod/ideas#146]
### Plugin description

Make audio files embed like in the PC version of Discord so that they are playable within the app instead of just being given the option to download.

Example PC embed:
![pc](https://github.com/vendetta-mod/ideas/assets/71614810/dc513aac-0c56-44b2-bd83-8099f95a2832)

(I believe there is a plugin like this available for Aliucord, but I could be wrong)

### ​

- [ ] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
CustomVoiceMessages has an option for it

**Comment by SixthByte** [comment]
> CustomVoiceMessages has an option for it

Oh ok, my bad then.
