### ISSUE TITLE
Pin Spotify/YouTube Music/Apple Music song on your profile

### ISSUE THREAD

**Issue by dora727** [vendetta-mod/ideas#147]
### Discord username

@dor4a

### Plugin description

A plugin that allow you pin your favorite song on any streaming service to your profile that anyone installed the plugin can see it
(I saw one on Enmity and I wish Vendetta also have one)

### Elaborate

Maybe, if we can put song on your profile without putting anything on profile like Enmity one to save bio characters (server-sided maybe is way costly but)
And would be nice if we can put using as more streaming services as possible!

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
grabbing this, seems like a very cool idea

**Comment by nexpid** [comment]
however pinned songs will only appear to people with the plugin

**Comment by dora727** [comment]
appreciate it!

**Comment by nexpid** [comment]
(forgot about this) https://vd-plugins.github.io/proxy/vendetta.nexpid.xyz/song-spotlight
