### ISSUE TITLE
show hidden channels (you can't open them, I know it impossible in Discord)

### ISSUE THREAD

**Issue by GabrielGreenWolf** [vendetta-mod/ideas#169]
### Plugin description

[HIDDEN CHANNELS WON'T SHOW INSIDE]

That plugin allows you to view hidden channels. Don't be nosy; it's impossible to see inside hidden channels in Discord.

### Elaborate

Just show hidden channels.

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
???? you can't read messages inside of channels you don't have access to (besides this plugin already exists)

**Comment by GabrielGreenWolf** [comment]
> ???? you can't read messages inside of channels you don't have access to (besides this plugin already exists)

1. Read title + description

2. "This plugin already exists" please post link here? 🤔

Edited: oops I saw, I couldn't find for some reason. Thank uwu

**Comment by nexpid** [comment]
oh i completely misread the title and description lol
