### ISSUE TITLE
SilentTyping

### ISSUE THREAD

**Issue by stressedapple** [vendetta-mod/ideas#175]
### Discord username

@sallyqwp

### Plugin description

It would be cool if I had the classic Silent Typing for Vendetta, one of my discord client plugins, that would hide the message I'm writing to others

### Elaborate

Adds a button, which when clicked, activates Silent Typing, something simple 

### ​

- [x] I have verified that this request is indeed original

**Comment by Totallynotmwa** [comment]
Great idea

**Comment by redstonekasi** [comment]
https://vd-plugins.github.io/proxy/redstonekasi.github.io/vendetta-plugins/no-typing/
already exists
