### ISSUE TITLE
BetterStatus 

### ISSUE THREAD

**Issue by DrLuxo** [vendetta-mod/ideas#182]
### Discord username

@_locy

### Plugin description

![IMG_0692](https://github.com/vendetta-mod/ideas/assets/96920429/bdde60dd-399f-479d-ad4a-f3e015794c8f)
Not much to say really, just that a status that can show off whether on mobile or pc and what type of mode they’re on.

### Elaborate

?

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
https://vd-plugins.github.io/proxy/martinz64.github.io/vendetta-plugins/PlatformIndicators
