### ISSUE TITLE
Constantly updating relative timestamps like on PC

### ISSUE THREAD

**Issue by ItsEnderium** [vendetta-mod/ideas#185]
### Discord username

itsenderium

### Plugin description

Relative timestamps behave just like on PC, where they constantly update.

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
https://vd-plugins.github.io/proxy/vendetta.nexpid.xyz/better-timestamps

**Comment by nexpid** [comment]
if you mean the <t:123:R> timestamps, then that isn't possible in Vendetta because chat is rendered natively
