### ISSUE TITLE
password

### ISSUE THREAD

**Issue by Celestemysterios** [vendetta-mod/ideas#186]
### Discord username

celestemyst

### Plugin description

basically it makes it to where you must enter a pin/password you set to enter into discord

### Elaborate

you might be wondering "why"
2 reasons i can think of
1. lets say someone stole someone elses phone and went and somehow got on the phone, this plugin could be extra security
2. ~~me dont want my parents going on it and seeing stuff~~

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Duplicate of #132
