### ISSUE TITLE
DOOM II

### ISSUE THREAD

**Issue by Celestemysterios** [vendetta-mod/ideas#189]
### Discord username

celestemyst

### Plugin description

basically the DOOM plugin but with DOOM 2

### Elaborate

maybe add myhouse (atleast the wad ver but if your able to somehow do the pk3 ver i will like you and give you cookie) 
also maybe add a selecter in the DOOM plugin to choose what DOOM you want to play

### ​

- [X] I have verified that this request is indeed original

**Comment by Celestemysterios** [comment]
~~i want to play more DOOM in discord~~

**Comment by Celestemysterios** [comment]
oh yeah also add support for saving if you can
please

**Comment by nexpid** [comment]
create a suggestion in my repo instead of here
https://github.com/nexpid/VendettaPlugins/issues/new/choose

**Comment by Celestemysterios** [comment]
oh ok
