### ISSUE TITLE
CharCounter

### ISSUE THREAD

**Issue by blank85** [vendetta-mod/ideas#2]
### Discord username

blank.#8012

### Plugin description

A CharCounter plugin like aliucord to see how much words we typed in text box

### Elaborate

It would be really good if someone makes this plugin 

### ​

- [X] I have verified that this request is indeed original

**Comment by Gabe616** [comment]
i'd like to work on this

**Comment by acquitelol** [comment]
> i'd like to work on this

you can patch chat input prototype most likely, and im pretty sure emoji keyboard module has a way to get the current input in the chat, so yes doable

**Comment by blank85** [comment]
I hate other keyboards, it would be more better if it was inside vendetta

**Comment by Gabe616** [comment]
> > i'd like to work on this
> 
> you can patch chat input prototype most likely, and im pretty sure emoji keyboard module has a way to get the current input in the chat, so yes doable

thank you rosie 
![image](https://github.com/vendetta-mod/ideas/assets/60316309/97b3951b-f6ce-4727-9df6-9c43537bbfcb)

**Comment by Gabe616** [comment]
> I hate other keyboards, it would be more better if it was inside vendetta

not like that, the counter will be above the chat text box

**Comment by blank85** [comment]
Please just add it it's not hard I guess 😭🫨

**Comment by Gabe616** [comment]
created a PR so you can check progress https://github.com/Gabe616/VendettaPlugins/pull/3

**Comment by blank85** [comment]
Doesn't work

**Comment by Gabe616** [comment]
# the plugin is finished
load it here (unproxied)
```
https://gabe616.github.io/VendettaPlugins/char-counter
```

**Comment by Gabe616** [comment]
@wingio can you mark this issue as resolved or something (and also pin the plugin link somehow)

**Comment by wingio** [comment]
As per the readme you have to get it proxied first

**Comment by wingio** [comment]
https://vd-plugins.github.io/proxy/gabe616.github.io/VendettaPlugins/char-counter/
