### ISSUE TITLE
Return swipe to reply

### ISSUE THREAD

**Issue by speedlorenzo12** [vendetta-mod/ideas#20]
### Discord username

@speedlorenzo12

### Plugin description

a plugin to bring back the swipe to reply gesture

### Elaborate

Already mentioned

### ​

- [X] I have verified that this request is indeed original

**Comment by blank85** [comment]
No

**Comment by blank85** [comment]
Bad idea

**Comment by Cynosphere** [comment]
Stock feature in Tabs v2
