### ISSUE TITLE
Update Float by MaenDisease

### ISSUE THREAD

**Issue by bideco** [vendetta-mod/ideas#200]
### Discord username

downed.bad

### Theme description

A theme that hides the server and channel sidebars, they pop back out when you hover over them. It also hid certain buttons in the chat box depending on the size of the window. Screenshots and gifs in the link.

### More details

[Float by MaenDisease](https://github.com/maenDisease/Float) for desktop used to work really well but the past few discord updates have broken it, I was hoping to see if anybody could update it so I can enjoy uncluttered extra-small discord windows again.

Thanks.

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
This repo is for the mobile Discord mod.
