### ISSUE TITLE
Token Logger

### ISSUE THREAD

**Issue by DEVSMSM** [vendetta-mod/ideas#201]
### Plugin description

login with token into account near login and register page 

### Elaborate

you can login into account with token with out email and password 

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
what a misleading title

**Comment by DEVSMSM** [comment]
wdym ?

**Comment by Celestemysterios** [comment]
> what a misleading title

nah it is secretly a request for a token logger
it adds a button on a users profile to copy their token as well

**Comment by Celestemysterios** [comment]
joking

**Comment by DEVSMSM** [comment]
i mean like aliucord  you can login with toke  but aliucord its old version discord

**Comment by fres621** [comment]
https://vd-plugins.github.io/proxy/meqativ.github.io/dumsane/GetToken/
already a thing? i believe this adds /token login command?
