### ISSUE TITLE
[Plugin]Call Counter

### ISSUE THREAD

**Issue by KrstlSkll69** [vendetta-mod/ideas#202]
### Discord username

@krystalskullofficial

### Plugin description

I think it would be good idea if someone made a call time counter{i dont even know if this is possible or not), but im thinking kinda like the one on vencord, or on bd

It would make keeping track of how long you have been a call for

**VENCORD**
https://vencord.dev/plugins/CallTimer

**BD**
https://betterdiscord.app/plugin/CallTimeCounter

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
#26
