### ISSUE TITLE
(NSFW)Channeltag

### ISSUE THREAD

**Issue by KrstlSkll69** [vendetta-mod/ideas#204]
### Discord username

@krystalskullofficial

### Plugin description

So, I don't even know if this is possible to do. But I have this .CSS code and i was wondering if it is possible to make a plugin that does the same thing/ mimics what it does

![Screenshot 2023-11-18 215417](https://github.com/vendetta-mod/ideas/assets/150982280/045dd2a3-9d9e-4962-842f-405d5faa2e2b)

Basically it adds a much more noticeable tag to "NSFW" channels. 
I only think its a good idea because its hard for my eyes to see the small little icon that discord as built in.\

Could work like the BD version-
https://betterdiscord.app/plugin/BetterNsfwTag

[I dont know how to show CSS code in this so hit me up on discord if you want to see it}

### ​

- [X] I have verified that this request is indeed original

**Comment by KrstlSkll69** [comment]
Didnt mean to close it i missed clicked

**Comment by ccrowles** [comment]
Was about to request the same thing, it always takes me a while to notice the really tiny icon.

**Comment by 7heMech** [comment]
I wanna claim this, working on it.

**Comment by KrstlSkll69** [comment]
Closing this because it was completed by the amazing @nexpid
_(also idk how to change the labels so sorry about that)_


https://vendetta.nexpid.xyz/nexxutils/
