### ISSUE TITLE
Relationship Notifier

### ISSUE THREAD

**Issue by Metercedes** [vendetta-mod/ideas#205]
### Discord username

-

### Plugin description

‘Relationships Notifier’ Discord plugin would serve to notify you of changes in your social connections. Specifically, it would alert you if someone removes you from their friend list or if you get kicked from a server.

Moreover, the plugin would include a log of these events accessible through an external menu in the settings. This log would provide details about who removed you and when it occurred, offering transparency and awareness of your social interactions within the Discord platform.

I hope this inspires someone:)

### Elaborate

The ‘Relationships Indicator’ Discord plugin operates by monitoring changes in your social connections. When someone removes you from their friend list or if you're kicked from a server, the plugin sends you a notification in real-time, ensuring you stay informed about these social dynamics.

For a more comprehensive view, the plugin features an external menu in the settings. This menu houses a detailed log of these events, allowing you to review a chronological record of who removed you and the precise timestamps of these actions. This additional functionality empowers users with insights into their social interactions on Discord, fostering transparency and enabling them to manage their connections effectively.

### ​

- [X] I have verified that this request is indeed original

**Comment by aeongdesu** [comment]
#4 duplicate
