### ISSUE TITLE
No sounds

### ISSUE THREAD

**Issue by dyrakfifa** [vendetta-mod/ideas#206]
### Discord username

qwersys_

### Plugin description

please make a plugin that turns off sounds: turning on the stream, turning on/off the microphone, joining a voice channel, etc.  Or like in bluecord, the same thing, but when the phone is on silent / vibration

### Elaborate

sounds while in the apk along the res/raw path

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Duplicate of #173
