### ISSUE TITLE
Enhancement for BetterChatGestures

### ISSUE THREAD

**Issue by XAlboX** [vendetta-mod/ideas#214]
### Discord username

@alboook

### Plugin description

The plugin should allow you to setup a custom function with a triple tap :3

### Elaborate

It would be cool if the plugin allowed you to translate other people's messages with a triple tap, reply to your own messages with a triple tap and edit them with a double tap.

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Suggestions for already existing plugins should be made on their respective repositories.
