### ISSUE TITLE
CSS Editor

### ISSUE THREAD

**Issue by Soheab** [vendetta-mod/ideas#215]
### Discord username

Soheab_

### Plugin description

I would like to suggest a CSS editor or something that can be used to modify stuff yourself. If possible.

### Elaborate

I imagine this being a section in settings with a text box that takes CSS and has the following buttons underneath: save/reload, remove all, enable/disable. Maybe also have autocomplete for the selectors etc if possible ofc. Kinda like "designing" a theme but then only locally, for yourself.

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Mobile doesn't use CSS in the same way that desktop does. I don't think its entirely possible since a lot of what would be classes are just hardcoded rules for the element.
