### ISSUE TITLE
Gif profile/server icons would always animate while using discord (like in discord for pc)

### ISSUE THREAD

**Issue by ELKirgeeUwU** [vendetta-mod/ideas#22]
### Discord username

Kirgee#0213

### Plugin description

The plugin would work like discord pc's gifs, it animates while you dont click on the server or open the user profile to display it 

### Elaborate

This plugin is more like Aliucord's Alwaysanimate, it's an plugin that makes the gifs from profile/server icon always animate

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Claiming

**Comment by acquitelol** [comment]
doesnt [this](https://github.com/Fierdetta/always-animate) already exist or am i understanding what theyre asking for wrong (it is unproxied i guess)

**Comment by wingio** [comment]
https://vd-plugins.github.io/proxy/cynosphere.github.io/VendettaPlugins/AlwaysAnimate/
