### ISSUE TITLE
Port SendTimestamps from Vencord

### ISSUE THREAD

**Issue by parkouristik93** [vendetta-mod/ideas#222]
### Discord username

@cabbagepigeon

### Plugin description

Basically adds a menu that lets you choose a date and paste it as timestamp. Screenshot is taken from Vencord
![изображение](https://github.com/vendetta-mod/ideas/assets/22059952/225b2c21-afb9-4c72-8235-15726c503d62)

### Elaborate

I kinda miss this feature when I decided to also download modded discord on my phone. This thing can help with coordination so much, especially in servers with a lot of users of different time zones

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
https://vd-plugins.github.io/proxy/vendetta.nexpid.xyz/better-timestamps/
