### ISSUE TITLE
Fake Profile effects and decorations 

### ISSUE THREAD

**Issue by Nonstopgaming75** [vendetta-mod/ideas#223]
### Plugin description

Pls remake this plug-in for vendetta too 
This plug-in gives prople ability to add to themselves both decorations and effects from nitro using 3y3 encoding 

### Elaborate

The plug-in is based on an experimental one of vencord : https://github.com/Vendicated/Vencord/pull/1930#pullrequestreview-1747340194

### ​

- [X] I have verified that this request is indeed original

**Comment by ryan-0324** [comment]
I have been planning to do this. Also, the plugin no longer uses just "3y3", which is just the tags unicode block (128 code points in the range U+E0000 to U+E007F inclusive). It now uses the entirety of U+E0000 to U+E0FFF inclusive (4096 code points).

**Comment by ryan-0324** [comment]
I have made a prototype version: https://github.com/ryan-0324/vendetta-plugins.
Currently, you must use the Vencord version to generate FPTE strings. I will add a UI for in-app FPTE string generation later.

**Comment by Rairof** [comment]
~~@ryan-0324 please update us with your progress~~
thanks

**Comment by Cynosphere** [comment]
https://vd-plugins.github.io/proxy/ryan-0324.github.io/vendetta-plugins/FakeProfileThemesAndEffects/
