### ISSUE TITLE
AutoStatus

### ISSUE THREAD

**Issue by SteveeTheCreeper** [vendetta-mod/ideas#228]
### Discord username

stevethecreeper

### Plugin description

Idk if it's possible, but maybe a plugin that auto updates the status to online when vendetta is opened
It happens to some devices without doing anything

### Elaborate

Basically online when vendetta is opened
Idle when leaving vendetta open for some time without doing anything
DND is optional and offline when vendetta is closed
Also I want it to update the status in the user pov like here

https://github.com/vendetta-mod/ideas/assets/119169182/8b33aa05-89b9-43c5-9928-c93ec7741327

I know some people say you can use self bot, but what about android people (me)

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
This is stock Discord functionality if you already have yourself set to online.
