### ISSUE TITLE
Material You

### ISSUE THREAD

**Issue by Tolga1452** [vendetta-mod/ideas#23]
### Discord username

@tolgchu

### Plugin description

This is actually a theme but themes are only json files so doing this with themes is impossible.

### Elaborate

Idk but if it's possible, it will use the selected colors on your phone by default. And of course we should be able to change the colors.

### ​

- [X] I have verified that this request is indeed original

**Comment by rickdtc** [comment]
Isnt this #21

**Comment by Tolga1452** [comment]
Ah yes, seems i missed that
