### ISSUE TITLE
Flowercord for Android

### ISSUE THREAD

**Issue by GNULain** [vendetta-mod/ideas#234]
### Discord username

GNULain

### Plugin description

There is a [tweak for Discord](https://github.com/acquitelol/rosiecord/tree/master/Tweaks/Flowercord) on iOS that is optional component for Rosiecord or Vendetta which adds square avatars and chat bubbles to the chat window. It would be nice to have this patched into Android as well to use as an optional component in Vendetta.

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
The reason its a tweak is because chat is rendered natively. It is impossible to do from Vendetta itself as a plugin. Even if someone were to port it as an Xposed module or something, it would be mod agnostic as is.

**Comment by mudrhiod** [comment]
Wouldn't flowercord come to android anyway when enmity V3 is released?

**Comment by Cynosphere** [comment]
No because it is an **iOS specific tweak** that modifies **native code**
