### ISSUE TITLE
Edit spoiler and alt text for images after they're sent

### ISSUE THREAD

**Issue by Nawhal** [vendetta-mod/ideas#236]
### Plugin description

Just as we can edit a sent message's text content, it would be great to be able to edit the alt text of an image or to put an image as spoiler after it has been sent.

### Elaborate

Maybe we could re use the already existing ui for when we upload images (the one that shows the options to put as spoiler and to enter an alt text), but while editing the message ? Or any other work-around way to be able to edit these things.
If it's not possible to edit messages with several images, being able to edit (spoiler + alt) the first image of a message would be great already. That would allow more ui possibilities.

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
API doesn't allow this, you can only remove attachments, not rename them or modify alt text.
