### ISSUE TITLE
Markdown Preview

### ISSUE THREAD

**Issue by IndigoSamurott** [vendetta-mod/ideas#24]
### Discord username

@indigosamurott

### Plugin description

This would be an implementation of Discord's text formatting within the chat input box, allowing the plugin's users to see how their markdown syntax will be rendered as they're typing it. 

### Elaborate

Ideally, it would act similarly to the functionality in the native desktop client! However, an alternative would be a button or option that creates a popup modal; this would mean the text doesn't need to be dynamically updated, and can show headers/masked links/etc.

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
i'd like to grab this

**Comment by blank85** [comment]
Best idea. Also @Gabe616 can't wait for this plugin lol

**Comment by nexpid** [comment]
created the PR on my github repo: https://github.com/Gabe616/VendettaPlugins/pull/4

# the plugin doesn't do anything yet, you can use the PR to track the progress of the plugin

**Comment by IndigoSamurott** [comment]
Awesome, thanks!

**Comment by nexpid** [comment]
current state of the plugin, please note it breaks char counter, will fix that later lol

https://github.com/vendetta-mod/ideas/assets/60316309/40edc62a-6ca3-43c5-9e38-69ac6da73963

**Comment by nexpid** [comment]
the actual markdown previewing isn't perfect so ill continue working on that

**Comment by blank85** [comment]
How do I download it

**Comment by nexpid** [comment]
> How do I download it

it's in the github pull request lol
![image](https://github.com/vendetta-mod/ideas/assets/60316309/04761528-da03-4196-83c5-e4dcfe55532f)

**Comment by IndigoSamurott** [comment]
This is looking great so far, thanks a ton for tackling it so rapidly

**Comment by nexpid** [comment]
I'd say the plugin is pretty much finished (only UI bugs are lists and charcounter incompatibility)

**Comment by nexpid** [comment]
![Screenshot_2023-07-01-14-01-48-489_dev.beefers.vendetta-edit.jpg](https://github.com/vendetta-mod/ideas/assets/60316309/b5f8e389-c631-48ea-9a90-dffe51636831)

![Screenshot_2023-07-01-14-01-32-813_dev.beefers.vendetta-edit.jpg](https://github.com/vendetta-mod/ideas/assets/60316309/94aeaad3-4b57-4756-9795-9531f2899147)

![Screenshot_2023-07-01-14-01-23-943_dev.beefers.vendetta-edit.jpg](https://github.com/vendetta-mod/ideas/assets/60316309/b22295a6-8815-46d7-a822-aa936138dcaa)

**Comment by nexpid** [comment]
# the plugin is finished
load it here (unproxied):
```
https://gabe616.github.io/VendettaPlugins/message-markdown-preview
```

**Comment by nexpid** [comment]
# preview

![Screenshot_2023-07-04-17-01-48-838_dev.beefers.vendetta-edit.jpg](https://github.com/vendetta-mod/ideas/assets/60316309/8b45edea-185b-48ae-b07e-cb8a7dde492e)

**Comment by nexpid** [comment]
ignore the strikethrough one i didn't realize

**Comment by IndigoSamurott** [comment]
Thanks a ton, the plugin's really good

For some reason though, headers stopped working in my previews after I updated:

![Screenshot_20230705_014858](https://github.com/vendetta-mod/ideas/assets/96881880/6fee29cb-e5c3-4c72-8467-707e7e001809)
#

**Comment by nexpid** [comment]
> Thanks a ton, the plugin's really good
> 
> For some reason though, headers stopped working in my previews after I updated:
> 
> ![Screenshot_20230705_014858](https://github.com/vendetta-mod/ideas/assets/96881880/6fee29cb-e5c3-4c72-8467-707e7e001809)
> #

I always use alpha, so just wait for Discord to update again and hopefully fix the header bug ![Screenshot_2023-07-05-08-28-14-207_dev.beefers.vendetta-edit.jpg](https://github.com/vendetta-mod/ideas/assets/60316309/bf584c38-98b4-4639-b6b0-cd7fe5d84806)

btw to answer your question, masked links will work once they're rolled out to you
