### ISSUE TITLE
Updating an existing plug-in 

### ISSUE THREAD

**Issue by KrstlSkll69** [vendetta-mod/ideas#242]
### Discord username

@krystalskulloffical

### Plugin description

I have a question: Do you think it would be possible to update this plug-in too make it so you can exclude certain people, bots, or even yourself?

https://vd-plugins.github.io/proxy/fierdetta.github.io/custom-timestamps/

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
[Ask on the plugin's repo](https://github.com/Fierdetta/custom-timestamps/issues/new)

**Comment by KrstlSkll69** [comment]
ok, can do, sorry
