### ISSUE TITLE
Hide this section on people’s accounts 

### ISSUE THREAD

**Issue by KrstlSkll69** [vendetta-mod/ideas#243]
### Discord username

krystalskullofficial

### Plugin description

The ability too hide the “Notes” section on people accounts. It’s stupid, weird, and i don’t think there is a single person who actually uses it. So let’s just remove it.
![IMG_4979](https://github.com/vendetta-mod/ideas/assets/150982280/3cd8c04f-96b5-4f8e-baae-df01aaa7aee8)

### ​

- [X] I have verified that this request is indeed original

**Comment by mollyvita** [comment]
sorry i use it 😞

**Comment by KrstlSkll69** [comment]
I dont know. I figured, this is something someone like 'nexpid' could add too their util plug-in as an optional niche thing

**Comment by KrstlSkll69** [comment]
> sorry i use it 😞

I dont know. I figured, this is something someone like 'nexpid' could add too their util plug-in as an optional niche thing

Kinda like the channel tag thing they did not too long ago

**Comment by nexpid** [comment]
> sorry i use it 😞

then just don't use the plugin

**Comment by KrstlSkll69** [comment]
> > sorry i use it 😞
> 
> then just don't use the plugin

brazy

Anyways... just an idea for something optional you could add to your util plugin, with how niche it is. just like the NSFW channel tag you made not too long ago
