### ISSUE TITLE
Text File Preview

### ISSUE THREAD

**Issue by IndigoSamurott** [vendetta-mod/ideas#28]
### Discord username

@indigosamurott

### Plugin description

As with the desktop client, it would be useful if text files (possibly below a certain size limit) sent in chat could be previewed. Long text files might need to have a smaller preview that can be expanded, and it would be useful if the contents could also be copied directly (whether by selecting parts in a popup modal or simply copying everything with a button).

### ​

- [X] I have verified that this request is indeed original

**Comment by fres621** [comment]
https://vd-plugins.github.io/proxy/fres621.github.io/vendetta-plugins/FileContentPreview/
