### ISSUE TITLE
Quick Restart

### ISSUE THREAD

**Issue by IndigoSamurott** [vendetta-mod/ideas#31]
### Discord username

@indigosamurott

### Plugin description

I'd love if a slash command, button at the top of the settings menu, or option in the Developer Settings (maybe multiple of those?) to instantly restart the app could be added. It would be a pleasant convenience when trying to fix app lag or plugins, avoiding the need to manually close and re-find Discord every time.

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
that's already in Settings > Vendetta > Reload Discord
