### ISSUE TITLE
Audio Player

### ISSUE THREAD

**Issue by IndigoSamurott** [vendetta-mod/ideas#32]
### Discord username

@indigosamurott

### Plugin description

The goal here would be to make .mp3 files - possibly other formats like .m4a too - playable and scrubbable within their Discord embed. This would bring more parity with the desktop app and be of general help when chatting.

### ​

- [X] I have verified that this request is indeed original

**Comment by rickdtc** [comment]
I think better voice notes olugin let's you play audio files as voice messages

**Comment by IndigoSamurott** [comment]
Aha, thanks! It's just on Custom Voice Messages then to hopefully implement `.m4a`s,  but either way a new plugin shouldn't be needed.

**Comment by balt-dev** [comment]
Do either of you have a link to the plugin that does this?

**Comment by balt-dev** [comment]
I found a plugin relationg to Voice Messages, but all it does is make mp3's that _I upload_ send as voice mesages.

**Comment by IndigoSamurott** [comment]
That's right, I didn't test thoroughly enough - CVM does make `.mp3`s playable, but only those sent by the user. 

@wingio should this issue be reopened or does it need to be implemented by the CVM plugin?

**Comment by ghost** [comment]
:nyaboom:

**Comment by wingio** [comment]
Just request it as a feature on the CVM repo

**Comment by rickdtc** [comment]
> That's right, I didn't test thoroughly enough - CVM does make `.mp3`s playable, but only those sent by the user.
> 
> @wingio should this issue be reopened or does it need to be implemented by the CVM plugin?

![Screenshot_20230713_005729](https://github.com/vendetta-mod/ideas/assets/74096544/d7522fad-44fa-4c0c-820f-189e807d7600)

You sure you have this option on?

**Comment by IndigoSamurott** [comment]
Oh my word, sometimes my incompetence knows no bounds.
Thank you so much for pointing that out :)
