### ISSUE TITLE
A multi-account plugin

### ISSUE THREAD

**Issue by thesh1xx** [vendetta-mod/ideas#34]
### Discord username

@thesh1xx

### Plugin description

Feature, to save accounts in the app, and just switch between accounts by some taps
(sorry for my english)

### ​

- [X] I have verified that this request is indeed original

**Comment by mollyvita** [comment]
this already exists as experiment and might be implemented by discord as working thing.
as for now, use experiments plugin to turn it on and use it :)

**Comment by Abinash-G** [comment]
But, this one is not that better like aliucord have
