### ISSUE TITLE
Now playing plugin

### ISSUE THREAD

**Issue by rickdtc** [vendetta-mod/ideas#37]
### Discord username

@knockdemput

### Plugin description

Don't know if the react native client can go this far but, a plugin that would read notification and detect the song playing and show it as rpc.

### ​

- [X] I have verified that this request is indeed original

**Comment by aeongdesu** [comment]
alternatively there is ~~[last.fm (unproxied)](https://amsyarasyiq.github.io/letup/Last.fm)~~ proxied version, check #plugins in discord server
