### ISSUE TITLE
Message Logger

### ISSUE THREAD

**Issue by baraa272** [vendetta-mod/ideas#38]
### Discord username

Biσμαρξκ#7726

### Plugin description

Message Logging 

### Elaborate

Message logger where it shows every change on all messages whether message is edited or deleted while showing those changes in real time and only FOR CURRENT SESSION 

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
There's 3 different message logger plugins that already exist

https://vd-plugins.github.io/proxy/redstonekasi.github.io/vendetta-plugins/message-logger/
https://vd-plugins.github.io/proxy/meqativ.github.io/dumsane/NoDelete/

unproxied dont use: https://angelix1.github.io/VP/message_logger/
