### ISSUE TITLE
FirstMessage

### ISSUE THREAD

**Issue by Not-Baguette** [vendetta-mod/ideas#39]
### Discord username

bagubaguu

### Plugin description

A plugin that creates a command to be executed in chat to find the first message on that channel/dm

### Elaborate

So this plugin will just create a new command like

`/firstmessage`

And it would return the link of the first message in that channel

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Already exists but is unproxied and potentially unfinished https://aeongdesu.github.io/vdplugins/FirstMessage/

**Comment by Not-Baguette** [comment]
> Already exists but is unproxied and potentially unfinished https://aeongdesu.github.io/vdplugins/FirstMessage/

I see, thank you for the response, didn't search hard enough. I will be closing this req
