### ISSUE TITLE
BetterHidenChannels

### ISSUE THREAD

**Issue by blank85** [vendetta-mod/ideas#42]
### Discord username

blan.k

### Plugin description

Someone made a hidden channels plugin but I don't know which one is a hidden channel and which one is a public channel, please someone make a better hidden channel plugin.

Like this
![Screenshot_20230703_100339](https://github.com/vendetta-mod/ideas/assets/137712947/3011d42f-5313-46a4-8b91-b907d397d89a)

### ​

- [X] I have verified that this request is indeed original

**Comment by wingio** [comment]
Suggest improvements and fixes in the existing plugins repo, not here.
