### ISSUE TITLE
Replace twemoji with system emoji

### ISSUE THREAD

**Issue by MegaCringe** [vendetta-mod/ideas#46]
### Discord username

@megacrng

### Plugin description

Replace the twemoji style emojis already seen on discord with the system default emojis (varies for whatever device) exactly like IOS.

### Elaborate

Twemoji style just sucks, would much rather prefer the system emojis.

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
nexpid here to grab yet another plugin idea :trolley:
this time the plugin is already finished
![Screenshot_2023-07-04-23-10-29-006_dev.beefers.vendetta-edit.jpg](https://github.com/vendetta-mod/ideas/assets/60316309/6f70faee-caf9-4758-9ca2-5ff522ae3c71)

**Comment by nexpid** [comment]
# the plugin is once again finished <:trolley:1068825486265942056>
load it here (unproxied):
```
https://gabe616.github.io/VendettaPlugins/use-system-emoji
```

(i know i'm not even assigned for this yet but the plugin is already finished anyway lol)

**Comment by nexpid** [comment]
btw always add unproxied plugins at your own risk, since they weren't verified by vendetta

**Comment by Leekawaii666** [comment]
I'm on 184.2.

**Comment by bleelblep** [comment]
I'm on Android 13, discord version 184.20 and I can't seem to enable the plugin

**Comment by MegaCringe** [comment]
@Gabe616 Is it possible to add an option to change the emoji scaling? I've noticed they (along with custom nitro emojis) appear smaller than they used to.

**Comment by nexpid** [comment]
> @Gabe616 Is it possible to add an option to change the emoji scaling? I've noticed they (along with custom nitro emojis) appear smaller than they used to.

afaik no, since jumbo emojis get put into a header (# ...) and I'm not sure if there's a way around that

**Comment by nexpid** [comment]
> I'm on Android 13, discord version 184.20 and I can't seem to enable the plugin

that's weird, could you send the "plugin will be unloaded" log from debug lots to #plugin-dev?

**Comment by mudrhiod** [comment]
Would you be able to make it apply to the discord emoji keyboard + reactions and so when we tap on them it shows the emoji

**Comment by wingio** [comment]
Since this request is complete im gonna suggest moving any further issues or requests to the plugins own repo

**Comment by nexpid** [comment]
> Would you be able to make it apply to the discord emoji keyboard + reactions and so when we tap on them it shows the emoji

https://github.com/Gabe616/VendettaPlugins/issues/new?assignees=&labels=suggestion&projects=&template=suggestion.yml&title=suggest%28use-system-emoji%29%3A+
