### ISSUE TITLE
Better Message Logger

### ISSUE THREAD

**Issue by cooolgamer** [vendetta-mod/ideas#47]
### Discord username

cooolboy

### Plugin description

There's already 2 existing plugins for this:
- Message Logger by redstonekasi,
- NoDelete by meqativ.

The thing is they both have issues:
- Message Logger does "message could not be loaded" if it's a reply and also log your own deleted message,
- Messages logged by No delete randomly disappear on a channel and you have to click twice to dismiss.

### Elaborate

The goal is to make a mix of those plugins to only preserve what's working, so fix the "message could not be loaded" reply of the Message Logger plugin that Nodelete doesn't have, also the same for logging your own deleted messages, it shouldn't be logged, just like Nodelete does.

### ​

- [x] I have verified that this request is indeed original

**Comment by MegaCringe** [comment]
Also add edit logging!

**Comment by wingio** [comment]
Leave suggestions and issues in the respective plugins repo, not here.
