### ISSUE TITLE
Sound Boards 

### ISSUE THREAD

**Issue by Amirsunrise** [vendetta-mod/ideas#52]
### Plugin description

Just a sound Board plugin like the Pc version of Discord 

### Elaborate

it would be great because we can finally use sound boards on mobile and we will no longer need to use The Web or Desktop version.

### ​

- [X] I have verified that this request is indeed original

**Comment by XAlboX** [comment]
You can activate the soundboard using the experiments plugin now :)!


[Screenshot_20230719-184848_Vendetta.png](https://github.com/vendetta-mod/ideas/assets/80044603/9ead8ba9-9ed4-44df-9e63-f9478e83114b)

**Comment by Amirsunrise** [comment]
> You can activate the soundboard using the experiments plugin now :)!
> 
> [Screenshot_20230719-184848_Vendetta.png](https://github.com/vendetta-mod/ideas/assets/80044603/9ead8ba9-9ed4-44df-9e63-f9478e83114b)



> You can activate the soundboard using the experiments plugin now :)!
> 
> [Screenshot_20230719-184848_Vendetta.png](https://github.com/vendetta-mod/ideas/assets/80044603/9ead8ba9-9ed4-44df-9e63-f9478e83114b)

**Comment by Amirsunrise** [comment]
> You can activate the soundboard using the experiments plugin now :)!
> 
> [Screenshot_20230719-184848_Vendetta.png](https://github.com/vendetta-mod/ideas/assets/80044603/9ead8ba9-9ed4-44df-9e63-f9478e83114b)

thanks but there is nothing for me in the experiments list

![Screenshot_2023-07-21-00-30-30-276_dev beefers vendetta](https://github.com/vendetta-mod/ideas/assets/110076470/c473e8af-80f9-4da0-97f0-41a44719dc4f)

**Comment by mollyvita** [comment]
> thanks but there is nothing for me

latest alpha maybe
