### ISSUE TITLE
Double click to edit / Double click to reply

### ISSUE THREAD

**Issue by yosefaljamal9999** [vendetta-mod/ideas#56]
### Discord username

@yousefalabdullah

### Plugin description

It's simple
on your sent message, you can double click on it to edit
or for message didn't send from you, double click on it to reply.

### Elaborate

It's not new but I didn't find it in the plugins list or suggestions but It's useful so I'm asking for it.

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
[BetterChatGestures](https://discord.com/channels/1015931589865246730/1092613163280769056)

**Comment by acquitelol** [comment]
its right at the bottom of the plugins list because it was one of the first plugins to be uploaded there lol

**Comment by nexpid** [comment]
rosie #1 plugin coder fr
