### ISSUE TITLE
Set Discord Activity (Rich Presence)

### ISSUE THREAD

**Issue by arguits** [vendetta-mod/ideas#57]
### Discord username

@arguits

### Plugin description

A plugin to set "Playing", "Listening", "Watching" in discord profile without PreMiD. I'll use the example of this extension for Chrome.
https://chrome.google.com/webstore/detail/set-discord-activity/dlmmhgaeahcfkojednnfghfpinbinicj
in Extension (only Chrome)
![Screenshot_20230709_190940_ReVanced Extended](https://github.com/vendetta-mod/ideas/assets/139021990/8fa73787-eb8c-40ca-9dc4-f3081b94de56)
in Profile
![Screenshot_20230709_191057_ReVanced Extended](https://github.com/vendetta-mod/ideas/assets/139021990/c65b5518-bd10-4653-bcc8-30f6ed688ba5)

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
a plugin that i'm already working on called CustomRPC
