### ISSUE TITLE
Auto @silent always used

### ISSUE THREAD

**Issue by Ann1kaB** [vendetta-mod/ideas#61]
### Discord username

@.mochaneko

### Plugin description

It would automatically use the @silent function when attempting to ping someone. Kind of like auto do not ping when replying to a message but not as a reply message.

### Elaborate

It could be done as an auto adding of the text @silent at the start of the text when the user types '@' followed by the user to be pinged/notified or invisible to the user and still uses the @silent function.

### ​

- [X] I have verified that this request is indeed original

**Comment by aeongdesu** [comment]
install [Text Replace](https://vd-plugins.github.io/proxy/fierdetta.github.io/text-replace/) and add this rule:
```json
{
    "name": "@silent",
    "match": "(^)+",
    "flags": "g",
    "replace": "@silent $1",
    "regex": true
}
```

**Comment by Ann1kaB** [comment]
> install [Text Replace](https://vd-plugins.github.io/proxy/fierdetta.github.io/text-replace/) and add this rule:
> 
> ```json
> {
>     "name": "@silent",
>     "match": "(^)+",
>     "flags": "g",
>     "replace": "@silent $1",
>     "regex": true
> }
> ```

That works, but now I wonder how we could make it easy for people to find this

**Comment by nexpid** [comment]
> > install [Text Replace](https://vd-plugins.github.io/proxy/fierdetta.github.io/text-replace/) and add this rule:
> > ```json
> > {
> >     "name": "@silent",
> >     "match": "(^)+",
> >     "flags": "g",
> >     "replace": "@silent $1",
> >     "regex": true
> > }
> > ```
> 
> That works, but now I wonder how we could make it easy for people to find this

text replace rule browser <:trolley:1068825486265942056>

**Comment by Ann1kaB** [comment]
> > > install [Text Replace](https://vd-plugins.github.io/proxy/fierdetta.github.io/text-replace/) and add this rule:
> > > ```json
> > > {
> > >     "name": "@silent",
> > >     "match": "(^)+",
> > >     "flags": "g",
> > >     "replace": "@silent $1",
> > >     "regex": true
> > > }
> > > ```
> > 
> > 
> > That works, but now I wonder how we could make it easy for people to find this
> 
> text replace rule browser <:trolley:1068825486265942056>

Is that a thing? If so where can I find it?

**Comment by aeongdesu** [comment]
there is no rule *browser* thing

btw please close this issue
