### ISSUE TITLE
Non-nitro Remix Media

### ISSUE THREAD

**Issue by cooolgamer** [vendetta-mod/ideas#62]
### Discord username

cooolboy

### Plugin description

Just as Client Themes plugin, but instead of unlocking nitro themes, it unlocks Remix Media even for Non-nitro user as it's pretty new and not everyone have it (it can be enabled on experiments).

### Elaborate

As the Remix Media is pretty new, I'm expecting the plugin to enable Remix Media experiment to unlock it from everyone, but also unlock it for non-nitro user. It also have to get the emojis and stickers unlocked if you want to add them on a picture (not sure if other plugins can break this).

### ​

- [X] I have verified that this request is indeed original

**Comment by cooolgamer** [comment]
This plugin was made thanks to Nyexx, here's the link for people who wants it: https://gabe616.github.io/VendettaPlugins/freemix (not proxied yet)

**Comment by nexpid** [comment]
@wingio mark this as finished pls
