### ISSUE TITLE
Hide Voice Message Button

### ISSUE THREAD

**Issue by yungsamd17** [vendetta-mod/ideas#63]
### Discord username

@yungsamd17

### Plugin description

Plugins that hides button for recording a voice message.

**Screenshot:**
![IMG_20230710_233232](https://github.com/vendetta-mod/ideas/assets/64147848/77467062-e593-46bc-bf33-673c678445e3)

### Elaborate

Pretty self explanatory, it just hides  _button for recording a voice message_ when plugin is enabled.

### ​

- [X] I have verified that this request is indeed original

**Comment by cooolgamer** [comment]
For now, you can use the experiments to disable voice messages as a workaround, but note that custom voice messages plugin will not work if you do this

**Comment by yungsamd17** [comment]
Thanks for reply, I'll try that.
