### ISSUE TITLE
Better Folders

### ISSUE THREAD

**Issue by MulverineX** [vendetta-mod/ideas#66]
### Discord username

MulverineX

### Plugin description

A port of [BetterFolders](https://github.com/Vendicated/Vencord/tree/main/src/plugins/betterFolders).

### Elaborate

The most important part for me is folder's automatically collapsing. I don't really care about the column design change.

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
https://vd-plugins.github.io/proxy/fres621.github.io/vendetta-plugins/BetterFolders/
