### ISSUE TITLE
Stereo

### ISSUE THREAD

**Issue by ghost** [vendetta-mod/ideas#67]
### Plugin description

A plugin that enables stereo in voice chats

### Elaborate

Enable stereo in voice chats making it possible to have 360 sound, left to right ear experience, the way it should've always been!

### ​

- [X] I have verified that this request is indeed original

**Comment by mollyvita** [comment]
not everybody has mic with "360 audio" support, to be more clear, almost nobody has them
also it should be supported by server-side. discord sends mono sound
we can't just "hey discord please send stereo just because we want to"

**Comment by ghost** [comment]
> not everybody has mic with "360 audio" support, to be more clear, almost nobody has them
> also it should be supported by server-side. discord sends mono sound
> we can't just "hey discord please send stereo just because we want to"

I thought it would be possible considering older discord versions and older modded clients have been able to use some sort of method to achieve stereo sound, not sure if the newer versions of discord now prevent, that hence your comment?
