### ISSUE TITLE
Favorite Media

### ISSUE THREAD

**Issue by KatayoX** [vendetta-mod/ideas#68]
### Plugin description

in Mobile app there is no option to add new gif to favorite, So please make plugin that will allow that & also you can add other feature like adding photos or video to favorite as well .. like this plugin of betterdiscord Named "FavoriteMedia" .

Thanks in advance

### ​

- [X] I have verified that this request is indeed original

**Comment by zykrah** [comment]
https://vd-plugins.github.io/proxy/castdrian.github.io/vendetta-plugins/favorite-gifs/
