### ISSUE TITLE
Better files picker

### ISSUE THREAD

**Issue by mudrhiod** [vendetta-mod/ideas#69]
### Discord username

moodalicious 

### Plugin description

Let user select which app to upload a file from.

### Elaborate

When you click the plus icon on chatbox and click files it opens google files (for android idk about iOS). i want a plugin that will let us choose the app we want by giving us a popup. (for example, google photos, system file picker, google drive etc etc)
afaik there was an aliucord plugin that did this so if you need more info on what i mean i can provide an SS.
![IMG_20230715_233234](https://github.com/vendetta-mod/ideas/assets/88912716/f210bd4d-2b76-445e-b0c2-1aa4034b8a13)
![IMG_20230715_233210](https://github.com/vendetta-mod/ideas/assets/88912716/d021aab1-b063-4652-aea9-f7a2bced2c5b)

### ​

- [X] I have verified that this request is indeed original

**Comment by nikosszzz** [comment]
![Screenshot_20230716_013535_Files.jpg](https://github.com/vendetta-mod/ideas/assets/53112175/6371f6a8-8671-456c-aa67-4f400cf61775)

I can normally pick any app to use on OneUI.

**Comment by mudrhiod** [comment]
I can do this too, but this is what i want.

![Screenshot_2023-07-15-23-45-13-42_c31b32364ce19ca8fcd150a417ecce58](https://github.com/vendetta-mod/ideas/assets/88912716/6df15241-413c-438a-a573-4a0011300431)

**Comment by nexpid** [comment]
@wingio this idea was grabbed by fres621

**Comment by wingio** [comment]
@fres621
