### ISSUE TITLE
Heic to png/jpg (?)

### ISSUE THREAD

**Issue by XAlboX** [vendetta-mod/ideas#72]
### Discord username

@alboook

### Plugin description

It would be nice to have a plugin that automatically changes the file extension during upload...

### Elaborate

Discord is dumb and doesn't understand that a heic file is a photo so it is uploaded as a file.
It has happened to me more than once to download a photo in heic format from Instagram and have to change the file extension.
Obviously not only for heic files...this was just an example...
If you have other file formats not recognized by discord please write them here.

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment]
Its not as simple as "rename the file extension and it automagically works". HEIC is a separate image format entirely.
The biggest issue is I don't know if there is a pure Javascript implementation of a converter.

HE-AAC audio encoded MP4 files are the only other file I know of that doesn't work properly within Discord.

**Comment by XAlboX** [comment]
Changing the file extension in the file explorer works :3 
I don't know if it actually corrupts any data in the file in anyway

**Comment by Cynosphere** [comment]
> Changing the file extension in the file explorer works

Because Windows already has an HEIC decoder and doesn't care what the extension is. You still can't upload it to Discord and expect it to work fine for everyone, especially the media proxy. If Discord('s media proxy) supported HEIC, it would already be embedding it.

**Comment by XAlboX** [comment]
I meant from Android .-.
I use Material Files as File Explorer

**Comment by Cynosphere** [comment]
Last two sentences still apply.

**Comment by Yeetov** [comment]
Just use a file converter like https://cloudconvert.com/heic-to-png

**Comment by XAlboX** [comment]
Thanks but it's no longer needed :3
