### ISSUE TITLE
Remove camera button 

### ISSUE THREAD

**Issue by mudrhiod** [vendetta-mod/ideas#73]
### Discord username

moodlnini

### Plugin description

Remove the camera button in photo picker.

### Elaborate

![Screenshot_2023-07-19-19-03-37-57_ce48f3669154ad2f53ee7715a6cfbfc3](https://github.com/vendetta-mod/ideas/assets/88912716/1829f8cd-304f-4b63-86f7-6506149e36e5)

### ​

- [X] I have verified that this request is indeed original

**Comment by Rairof** [comment]
Or instead of removing it, we can use that space to add something actually useful like this-
![IMG_20230826_185044](https://github.com/vendetta-mod/ideas/assets/107706560/05bd5315-98d2-421b-89a1-cc9e2ff073af)
Any thoughts @nexpid?
And just grey it out when Spotify is not running...

**Comment by mudrhiod** [comment]
I like this idea

**Comment by nexpid** [comment]
grabbing this for nexxutils

**Comment by Rairof** [comment]
> grabbing this for nexxutils

Lmao you're welcome!

**Comment by nexpid** [comment]
progress

https://github.com/vendetta-mod/ideas/assets/60316309/20a6579a-6157-4d91-9414-b2fcaf61b89b

**Comment by Rairof** [comment]
> progress
> 
>  Screenrecorder-2023-08-27-14-49-18-759.mp4

OMG CANT WAIT TO GET IT!!

**Comment by Rairof** [comment]
> progress
> 
>  Screenrecorder-2023-08-27-14-49-18-759.mp4

Can you give some sort of pop up instead of directly sending the invite like that, similar to how it works on desktop discord? That will be nice if possible

**Comment by nexpid** [comment]
> > progress
> > Screenrecorder-2023-08-27-14-49-18-759.mp4
> 
> Can you give some sort of pop up instead of directly sending the invite like that, similar to how it works on desktop discord? That will be nice if possible

not sure, might just keep it at insta-sending

**Comment by nexpid** [comment]
here's how the button looks like active vs inactive
| | |
|-|-|
| ![image](https://github.com/vendetta-mod/ideas/assets/60316309/dc4ace12-14a5-4c89-b752-816703585267) | ![image](https://github.com/vendetta-mod/ideas/assets/60316309/04f9a3ea-1fcc-43fb-a518-8dc3ba52b2c7) |

also added to NexxUtils, https://vendetta.nexpid.xyz/nexxutils

**Comment by nexpid** [comment]
@Cynosphere finished btw

**Comment by mudrhiod** [comment]
Thnx nexx

**Comment by Rairof** [comment]
Thanks a lot nexpid
