### ISSUE TITLE
Attachment remover.

### ISSUE THREAD

**Issue by Gdrugdryjff** [vendetta-mod/ideas#75]
### Discord username

Spoilerinoo

### Plugin description

A plugin that allows you to remove attachments from your message like you can do on PC. Not sure if that's possible but would be cool.

### ​

- [X] I have verified that this request is indeed original

**Comment by aeongdesu** [comment]
https://vd-plugins.github.io/proxy/c10udburst-discord.github.io/vendetta-plugins/delete-embeds/
