### ISSUE TITLE
Accurate Timestamps

### ISSUE THREAD

**Issue by Karguy1** [vendetta-mod/ideas#8]
### Plugin description

Make the timestamps on messages more accurate.

### Elaborate

It should show the date and time the message was sent down to the second. It would also be cool if you could manually edit the timestamp format like customtimestamps on aliucord, or it could just be accurate like complete timestamps on betterdiscord.

### ​

- [X] I have verified that this request is indeed original

**Comment by jackmthws** [comment]
claiming

**Comment by jackmthws** [comment]
https://vd-plugins.github.io/proxy/fierdetta.github.io/custom-timestamps/
