### ISSUE TITLE
Copy image/gif URL

### ISSUE THREAD

**Issue by nemodynia** [vendetta-mod/ideas#81]
### Discord username

@Nemesis306

### Plugin description

A button that lets you copy image URL on image context menu. Yeah, that's it.

### ​

- [X] I have verified that this request is indeed original

**Comment by XAlboX** [comment]
Just click Share and than Copy

**Comment by nexpid** [comment]
ximi phones don't have copy
![Screenshot_2023-07-25-08-13-08-641_android-edit.jpg](https://github.com/vendetta-mod/ideas/assets/60316309/a48eee9d-441e-489f-9162-210e14482553)

**Comment by XAlboX** [comment]
Blame MIUI then 🔥

**Comment by nexpid** [comment]
OP you can use this https://play.google.com/store/apps/details?id=com.tengu.sharetoclipboard

**Comment by aeongdesu** [comment]
you dont need anything, just long press the image in chat

![Screenshot_20230725_155425](https://github.com/vendetta-mod/ideas/assets/50764666/be09ce40-5d7b-4baa-9782-33863e2fb571)

**Comment by nexpid** [comment]
> you dont need anything, just long press the image in chat
> 
> ![Screenshot_20230725_155425](https://github.com/vendetta-mod/ideas/assets/50764666/be09ce40-5d7b-4baa-9782-33863e2fb571)
> 

dhare to clipboard is still useful for other apps

**Comment by nemodynia** [comment]
> you dont need anything, just long press the image in chat
> 
> ![Screenshot_20230725_155425](https://user-images.githubusercontent.com/50764666/255815871-be09ce40-5d7b-4baa-9782-33863e2fb571.png)

oh lol, i've just noticed this now
so i guess thanks?
