### ISSUE TITLE
ShowHiddenChannels rewrite

### ISSUE THREAD

**Issue by yofukashino** [vendetta-mod/ideas#82]
### Discord username

loneweeb.tsx

### Plugin description

a rewrite on current hidden channels plugin with features like removing unread from channels. adding hidden indicators on channel item in channel list. a better fancier hidden channels page maybe.
well since it's react native and you should be able recreate whatever in on pc as a mobile version with different styling since the props would stay same, what I want to say pls add same features as the one I have on replugged version.
I can write one but someone is already working idk so leaving this here, if no one responds by Aug 15 I will do this myself.
Happy independence day to my fellow Indians in advance.
Love from India <3

### Elaborate

do what's replugged's hidden channels plugin could do 

### ​

- [X] I have verified that this request is indeed original

**Comment by wingio** [comment]
This should be requested on the plugins own repo

**Comment by yofukashino** [comment]
> This should be requested on the plugins own repo

they don't even respond on discord's plugin forum on pings. I tried, the plugin is abandoned so here is the right place

**Comment by Cynosphere** [comment]
You can always try [making an issue on their repo](https://github.com/c10udburst-discord/vendetta-plugins/issues/new/choose)
