### ISSUE TITLE
Regular Discord AMOLED Recreation

### ISSUE THREAD

**Issue by viiuan** [vendetta-mod/ideas#83]
### Theme description

if there could be specifically a Ventetta theme replicating the vanilla Discord AMOLED theme that would be swag
i just ideally want to use the vanilla AMOLED rather than existing amoled themes
considering vanilla AMOLED is currently borked in the latest alpha as of when this post was made
just nicer for me to rely on a theme i know will work between versions yk

### ​

- [X] I have verified that this request is indeed original

**Comment by mollyvita** [comment]
i don't think vendetta mods will approve this theme tho, it's just copying 
but that's on their side, i wont do it btw, don't have any time rn :(

**Comment by TakiShiwa** [comment]
What! Explain me with screenshots, and what did they do, did they kill something in latest beta?

**Comment by mollyvita** [comment]
> What! Explain me with screenshots, and what did they do, did they kill something in latest beta?

latest alpha, not beta

**Comment by cooolgamer** [comment]
Yes they killed it, enabling it does nothing now, and combining it with themes (I tested with one that make buttons pink), it become completely transparent on user settings

**Comment by Cynosphere** [comment]
https://git.mylloon.fr/Anri/confOS/raw/branch/main/themes/VendettaOLED.json

**Comment by viiuan** [comment]
THANK YOU 🙏🙏🙏💯💯💯🔥🔥🔥
