### ISSUE TITLE
Foreign Lettering in Username(s)

### ISSUE THREAD

**Issue by daedaevibin** [vendetta-mod/ideas#84]
### Discord username

♡DaeDae♡

### Plugin description

Request: A plugin to allow the user to add foreign letters to the username instead of strictly English.

In my case, I'm wishing to use the Korean Alphabet for a username. It's not allowed at all.

### Elaborate

This plugin should supports as many languages as possible but places to start would be Korean, Japanese, Arabic, and Chinese. I hope this goes somewhere. Thanks again

### ​

- [ ] I have verified that this request is indeed original

**Comment by ghost** [comment]
This is impossible;
![image](https://github.com/vendetta-mod/ideas/assets/105166639/cb64e4d3-1fbf-4dfc-a001-c977a19dc7e0)

**Comment by daedaevibin** [comment]
> This is impossible;
> ![image](https://github.com/vendetta-mod/ideas/assets/105166639/cb64e4d3-1fbf-4dfc-a001-c977a19dc7e0)
> 

![SmartSelect_20230725_204112.jpg](https://github.com/vendetta-mod/ideas/assets/134977461/ee2b4569-b99f-4402-bf08-5760f1520a6e)

This is what I receive every time I try.

**Comment by ghost** [comment]
There is no way to bypass this, are display names not suitable for you?

**Comment by daedaevibin** [comment]
Sent: 2023.07.25 PM 08:44:49 (GMT-05:00)
Subject: Re: [vendetta-mod/ideas] Foreign Lettering in Username(s) (Issue #84)

There is no way to bypass this, are display names not suitable for you?
