### ISSUE TITLE
Remove "Invite to servers" 

### ISSUE THREAD

**Issue by EngieTheProto** [vendetta-mod/ideas#85]
### Discord username

engietheproto

### Plugin description

A simple plugin that removes the "Invite to servers" button that shows up on user profiles

### Elaborate

Nothing else to add, it's just a simple plugin idea

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
i could add this to NexxUtils (unproxied and unfinished)
![image](https://github.com/vendetta-mod/ideas/assets/60316309/1268c6fc-1c01-4735-804e-55a093ed43ef)

**Comment by nexpid** [comment]
@wingio can i grab this (i'll add it to nexxutils)

**Comment by nexpid** [comment]
done
```
https://gabe616.github.io/VendettaPlugins/nexxutils/
```
![image](https://github.com/vendetta-mod/ideas/assets/60316309/846f9fea-a4e5-4899-ae9f-e6a95fda9be4)

**Comment by EngieTheProto** [comment]
yay :3
