### ISSUE TITLE
Reaction Notifier 

### ISSUE THREAD

**Issue by Kazokiss** [vendetta-mod/ideas#86]
### Plugin description

Gives an notification for when someone reacts to your message. 

### Elaborate

Here's an image. 
![SmartSelect_20230728_021649](https://github.com/vendetta-mod/ideas/assets/140789371/4803d1e5-66cb-45b6-80e8-c6a85272fd1a)
![Screenshot_20230728_023117](https://github.com/vendetta-mod/ideas/assets/140789371/6b793975-3dce-4991-94e6-465d362889aa)

### ​

- [x] I have verified that this request is indeed original

**Comment by nexpid** [comment]
grabbing this since i was already working on this before

**Comment by nexpid** [comment]
@Cynosphere could this be closed (it's impossible)
