### ISSUE TITLE
ClearVision - Theme

### ISSUE THREAD

**Issue by razeNFR** [vendetta-mod/ideas#87]
### Discord username

@razenfr

### Theme description

Much better description than my words, the theme is here : https://betterdiscord.app/theme/ClearVision

### More details

Sorry my english is very bad, but i think we can take the base of VioletSkie theme already in Vendetta Manager Discord, and edit some colors and background to match to the ClearVision theme :) 

### ​

- [X] I have verified that this request is indeed original

**Comment by TakiShiwa** [comment]
Do you have any screenshots, I could not find one

**Comment by razeNFR** [comment]
> 

https://betterdiscord.app/Image/176

**Comment by TakiShiwa** [comment]
Ok ill make it

**Comment by TakiShiwa** [comment]
Vendetta has some limitations regarding transparency, keep that in mind.

**Comment by razeNFR** [comment]
Thank you so much to make it, and yes i know transparency is not possible

**Comment by TakiShiwa** [comment]
<u> Nice </u>
Pleasures are mine

**Comment by razeNFR** [comment]
Can i have your Discord nickname, to watch the progression of the theme ? And maybe helping if i can ☺️

**Comment by TakiShiwa** [comment]
> Can i have your Discord nickname, to watch the progression of the theme ? And maybe helping if i can ☺️

I am admitted to the hospital right now , so I haven't started yet

**Comment by razeNFR** [comment]
Ho damn, I'm sorry for you, I hope you don't have anything serious and that you will recover quickly

**Comment by TakiShiwa** [comment]
> Ho damn, I'm sorry for you, I hope you don't have anything serious and that you will recover quickly

I started work, coming soon.

**Comment by razeNFR** [comment]
Nice ! I can't wait to see the result, if you need color idea or others, do not hesitate 😊

**Comment by TakiShiwa** [comment]
> Nice ! I can't wait to see the result, if you need color idea or others, do not hesitate 😊

Done
Completed in one day 😎

**Comment by TakiShiwa** [comment]
completed
