### ISSUE TITLE
WhoReacted - See who react faster

### ISSUE THREAD

**Issue by razeNFR** [vendetta-mod/ideas#88]
### Discord username

@razenfr

### Plugin description

![229246491-bb572a18-7e09-4457-ac20-b51e0fb05923](https://github.com/vendetta-mod/ideas/assets/71156828/b136b15b-656d-43e2-aece-89fc5e17e801)

I think the screenshot gives all the information about the interest of the plugin, otherwise I send a link to the BetterDiscord plugin. (https://betterdiscord.app/plugin/WhoReacted)

### ​

- [x] I have verified that this request is indeed original

**Comment by nexpid** [comment]
don't think this is possible because message reactions are renderer natively

**Comment by nyncral** [comment]
and how would you see it if there are like 500 reactions?

**Comment by razeNFR** [comment]
Like the WhoReacted from Betterdiscord, no more than 4 or 5 pictures

**Comment by nexpid** [comment]
> this is impossible because message reactions are rendered natively

**Comment by razeNFR** [comment]
Yeah we can close this post
