### ISSUE TITLE
Nitroless sticker sending

### ISSUE THREAD

**Issue by skullhunter0x7** [vendetta-mod/ideas#9]
### Plugin description

Being able to send stickers without having nitro

### Elaborate

Would be great if you could send them as an image or gif, but links or something could work (i know nothing about development or how discord handles things

But sending stickers as gifs or pngs would be great

### ​

- [X] I have verified that this request is indeed original

**Comment by mollyvita** [comment]
[already exists](https://aliernfrog.github.io/vd-plugins/FreeStickers/) but not proxied yet
also still doesn't have ability to convert sticker apng to gifs

**Comment by redstonekasi** [comment]
https://vd-plugins.github.io/proxy/aliernfrog.github.io/vd-plugins/FreeStickers/
