### ISSUE TITLE
Copy role color

### ISSUE THREAD

**Issue by mstudio45** [vendetta-mod/ideas#90]
### Discord username

mstudio45

### Plugin description

A plugin that shows a menu (like the one when you click the three dots in someone's profile) when you click a role in someone's profile (in a server) with two buttons: "Copy role ID", "Copy role color". The "Copy role color" would copy the role's color in hex.

### ​

- [X] I have verified that this request is indeed original

**Comment by Martinz64** [comment]
i'm taking this plugin

**Comment by Martinz64** [comment]
https://github.com/vendetta-mod/ideas/assets/24656265/fbecb217-c62f-41a3-a225-335225473d4f

got this working

**Comment by mstudio45** [comment]
nice, thanks!

**Comment by Cynosphere** [comment]
https://vd-plugins.github.io/proxy/martinz64.github.io/vendetta-plugins/CopyRoleColor/

**Comment by mstudio45** [comment]
Thanks!
