### ISSUE TITLE
GoogleEmojis

### ISSUE THREAD

**Issue by MarselTheLynx** [vendetta-mod/ideas#94]
### Discord username

@midicat228

### Theme description

Replaces the default Tweemoji emotes with the ones from Google. I am not sure if this is possible though

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment]
an alternative to this is my UseSystemEmoji plugin but replacing the emoji font like this is impossible

**Comment by MarselTheLynx** [comment]
> an alternative to this is my UseSystemEmoji plugin but replacing the emoji font like this is impossible

Is it a plugin? And where can I download it? I haven't seen it on the Vendetta server

**Comment by nexpid** [comment]
> > an alternative to this is my UseSystemEmoji plugin but replacing the emoji font like this is impossible
> 
> Is it a plugin? And where can I download it? I haven't seen it on the Vendetta server

https://vd-plugins.github.io/proxy/gabe616.github.io/VendettaPlugins/use-system-emoji/
